version: '3.8'

services:
  frontend:
    labels:
      shipyard.route: '/'
    build: '.'
    environment:
      CI: 'true'
      DANGEROUSLY_DISABLE_HOST_CHECK: 'true'
    env_file:
      - ./.env
    volumes:
      - '.:/src'
    ports:
      - '3000:3000' # React app
      - '3001:3001' # JSON server
